// <auto-generated />
using System;
using FC.Caixa.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FC.Caixa.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240927022617_RemoverDadosTabela2")]
    partial class RemoverDadosTabela2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FC.Caixa.Domain.Models.MovimentacaoCaixa", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("datamovimentacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("tipo")
                        .HasColumnType("integer");

                    b.Property<decimal>("valor")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.ToTable("movimentacoes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
